Feature/issue 871
wielebenwir/commonsbooking pull request #1028
Opened 2022-04-26 20:00 UTC by chriwen

2022-05-02 15:41 UTC, hansmorb commented
Also Buchungen im Backend bearbeiten geht, leider fehlt mir im Backend noch der "Buchung hinzufügen" Button

2022-05-03 17:09 UTC, chriwen commented
@hansmorb Jetzt sollte es klappen. Bitte beachte, dass bei Buchungen nur der Button "save as draft" zur Verfügung steht. Der gewünschte Buchungsstatus (confirmed) muss manuell über den Status-Edit erfolgen. Ich ergänze dazu noch einen Doku-Artikel. 
Schau doch mal, ob das bei dir nun passt.

2022-05-10 16:12 UTC, hansmorb commented
Also bei mir klappt das noch nicht. Wenn ich eine Buchung komplett "from scratch" im Backend erstelle, dann wird mir der entsprechende Zeitraum nicht als geblockt angezeigt. Es fehlen auch einige Meta Keys, die bei einer regulären Buchung dabei sind.

Siehe reguläre Buchung:

![image](https://user-images.githubusercontent.com/6433480/167674341-ab1c43c1-d02f-4659-a49d-2b9694742a88.png)


vs. Backend Buchung:

![image](https://user-images.githubusercontent.com/6433480/167674390-4bcfd28b-f5fb-4637-a05a-3ad43a794622.png)

2022-07-01 11:25 UTC, markus-mw commented
> Also bei mir klappt das noch nicht. Wenn ich eine Buchung komplett "from scratch" im Backend erstelle, dann wird mir der entsprechende Zeitraum nicht als geblockt angezeigt. Es fehlen auch einige Meta Keys, die bei einer regulären Buchung dabei sind.
> 
> Siehe reguläre Buchung:
> 
> ![image](https://user-images.githubusercontent.com/6433480/167674341-ab1c43c1-d02f-4659-a49d-2b9694742a88.png)
> 
> vs. Backend Buchung:
> 
> ![image](https://user-images.githubusercontent.com/6433480/167674390-4bcfd28b-f5fb-4637-a05a-3ad43a794622.png)

Jagut, das ist normal, weil die Felder ganz einfach nicht im Formular sind. Wenn eine echte Buchung erzeugt wird, werden dabei Infos des Timeframes übernommen. Damit die einstellbar sind, müssten wir sie wieder im Formular der Buchung ergänzen, das führte aber immer wieder zu Problemen...
Hier die Stelle an der die Infos des Timeframes übernommen werden: 
\CommonsBooking\Model\Booking::assignBookableTimeframeFields

2022-07-01 11:33 UTC, chriwen commented
@markus-mw ich denke es reicht wenn wir nur die Felder haben die für Buchung relevant sind. Diese sollten halt mit den übers Fronten generierten identisch sein. Ist das momentan so oder gäbe es da Unterschiede? Das einzige was ich sehe ist die start-time und end-time. Wo werden die verwendet und wie könnten wir sie in die backend Buchung einbauen?

2022-07-01 11:50 UTC, markus-mw commented
@chriwen : Die _start-time_ und _end-time_ Felder werden für die Prüfung benötigt, ob sich Buchungen überlappen. Die _full-day_ Einstellung wird für die Ausgabe von Abholung/Rückgabe benötigt aber auch für die Prüfung von buchbaren Slots. Auch das _grid_ Feld wird an verschiedenen Stellen (Slotbelegung, Abholung/Rückgabe) benötigt.
Wir hatten die ganzen Felder mal einstellbar, uns aber dann entschieden sie rauszunehmen. Von mir aus machen wir die alle wieder rein, das muss dann aber gründlich getestet werden. Wie gesagt meine ich, gab das Probleme, wenn da übers Backend dran rumgepfuscht wurde.

2023-01-04 13:40 UTC, hansmorb requested changes

2023-01-04 13:40 UTC, hansmorb commented on src/Wordpress/CustomPostType/Booking.php
> +    public static function getFrontendBookingAuthor() {
Fände die Helper Funktion auch praktisch, vielleicht könnte man die einfach getOwner nennen und die auf das Booking Model anwenden? Dann müsstest du nicht über das Post Object zugreifen sondern könntest das über das Model machen

2023-01-20 21:07 UTC, chriwen commented on src/Wordpress/CustomPostType/Booking.php
> +    public function RemoveAuthorField() {
ok :-)

2023-01-20 21:20 UTC, chriwen commented on src/Wordpress/CustomPostType/Booking.php
> +    public static function getFrontendBookingAuthor() {
ok, schau ich mir mal an, wobei ich denke, dass inhaltlich der Author etwas genauer ist, um klar zu machen, das wir hier mit dem WP-Post-Author arbeiten. Owner haben wir ja im Kontext von Buchungen bisher nicht, oder?

2023-03-09 15:53 UTC, hansmorb commented on includes/Admin.php
> +    if (WP_DEBUG_LOG != true ) {
Oder lieber ( ! WP_DEBUG_LOG) ? Ist aber auch nicht so wichtig

2023-03-09 16:16 UTC, hansmorb requested changes

2023-03-09 16:16 UTC, hansmorb commented on src/Wordpress/CustomPostType/Booking.php
> +	protected static function returnExistingBookings( $itemId, $locationId, $startDate, $endDate, $postId = null ) {
Hmm, das wäre eher was fürs repository, oder? Und dann vielleicht sowas wie Booking::getOverlapping scheint mir sinnig

2023-03-09 16:33 UTC, chriwen commented on src/Messages/AdminMessage.php
> +    private $message;
ok

2023-03-09 21:17 UTC, chriwen commented on src/Wordpress/CustomPostType/Booking.php
> +	protected static function returnExistingBookings( $itemId, $locationId, $startDate, $endDate, $postId = null ) {
ja, hast recht. Können wir das einfach so verschieben?

2023-03-10 09:36 UTC, chriwen commented on src/Wordpress/CustomPostType/Booking.php
> +                      '<div style="background-color:#e6aeae; padding:20px; border:5px solid red"><h2>' . commonsbooking_sanitizeHTML(
im Prinzip brauchts das nicht, hast recht. Ist auch stylemäßig nicht die sauberste Lösung das hier Inline zu definieren (aber die schnellste ;-) ) 
Hintergrund war, dass ich in der Vergangenheit schon öfter Supportanfragen hatte, deren Lösung es gewesen wäre die kleine aber feine Fehlermeldung zu lesen. Und da dachte ich, mache ich die in diesem Fall mal besonders deutlich ;-)
Kann ich aber auch hier nochmal rausnehmen. Bei den Overlapping-Meldung würd ichs aber so prominent drinlassen.

2023-03-10 09:57 UTC, hansmorb commented on src/Wordpress/CustomPostType/Booking.php
> +                      '<div style="background-color:#e6aeae; padding:20px; border:5px solid red"><h2>' . commonsbooking_sanitizeHTML(
Ooooder wir stylen einfach alle ein bisschen fetter. Wir können ja auch für unsere Meldungen ne eigene CSS Klasse anlegen und dann sehen alle gleich groß aus.

2023-03-17 13:12 UTC, hansmorb commented on src/Plugin.php
> +        add_filter( 'gettext', 'commonsbooking_translate_words_array' );
Huch, das ist jetzt aber neu, oder? Ist das diese Möglichkeit jeden beliebigen String zu bearbeiten?

2023-03-17 13:15 UTC, hansmorb commented on src/Plugin.php
> +        add_filter( 'gettext', 'commonsbooking_translate_words_array' );
Ah ne, bin blöd, verstehe das erst jetzt. Uff, ich bin mir arg unsicher, jeder übersetzte String wird ja dann durch diese Funktion gejagt, oder? Also aus der ganzen Webseite.

2023-03-17 22:14 UTC, hansmorb commented on src/Plugin.php
> +        add_filter( 'gettext', 'commonsbooking_translate_words_array' );
Achso, jetzt haste dit ganz entfernt, so meinte ich dit ooch nicht. Ich wollte nur fragen ob es da vielleicht ne Alternative gibt.

2023-03-29 20:33 UTC, chriwen commented on src/Repository/Booking.php
> +		array_filter( $existingBookingsInRange, fn( $booking ) => $booking->ID !== $postId );
erledigt

2023-03-29 20:34 UTC, merged