Bugfix/issue 1031
wielebenwir/commonsbooking pull request #1032
Opened 2022-05-04 16:01 UTC by chriwen

2022-05-06 11:57 UTC, markus-mw requested changes

2022-05-06 11:57 UTC, markus-mw commented on src/Migration/Migration.php
> +            $location->to_array(),
Da ist deine Autoformatierung aber eskaliert. Kannst du das bitte wieder etwas netter einrücken?

2022-05-06 11:57 UTC, markus-mw commented on src/Migration/Migration.php
> +            $words,
Hier bitte auch wieder sauber einrücken.

2022-05-06 11:57 UTC, markus-mw commented on src/Migration/Migration.php
> +            [
Wieder Einrückung...

2022-05-11 12:09 UTC, hansmorb approved these changes

2022-05-12 13:54 UTC, merged