Feature/issue 1048
wielebenwir/commonsbooking pull request #1049
Opened 2022-05-17 08:33 UTC by chriwen

2022-05-20 12:04 UTC, markus-mw requested changes

2022-05-20 12:04 UTC, markus-mw commented on includes/TemplateParser.php
> +    if ( preg_match_all( '/{{.*?}}/', $template ) === 0 ) {
Den Teil aus den Zeilen 14-20 braucht es doch dann gar nicht mehr, oder?

2022-07-08 11:20 UTC, markus-mw approved these changes

2022-07-08 11:20 UTC, merged

2022-07-08 11:25 UTC, chriwen commented
@markus-mw oh. Ich sehe gerade dass das in 2.7.2 gemerged wurde. 2.7.2 ist ja bereits Released. Kannst du das nochmal in den Master mergen?

2022-07-08 11:28 UTC, markus-mw commented
Erledigt.

 

Von: christian-wlw ***@***.***> 
Gesendet: Freitag, 8. Juli 2022 13:26
An: wielebenwir/commonsbooking ***@***.***>
Cc: markus-mw ***@***.***>; Mention ***@***.***>
Betreff: Re: [wielebenwir/commonsbooking] Feature/issue 1048 (PR #1049)

 

@markus-mw <https://github.com/markus-mw>  oh. Ich sehe gerade dass das in 2.7.2 gemerged wurde. 2.7.2 ist ja bereits Released. Kannst du das nochmal in den Master mergen?

—
Reply to this email directly, view it on GitHub <https://github.com/wielebenwir/commonsbooking/pull/1049#issuecomment-1178876083> , or unsubscribe <https://github.com/notifications/unsubscribe-auth/AFOYHGMXLWI7WRB7S2TXWYLVTAF4HANCNFSM5WEC3WPQ> .
You are receiving this because you were mentioned.  <https://github.com/notifications/beacon/AFOYHGP6VTRQWXSLRXRZ3O3VTAF4HA5CNFSM5WEC3WP2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOIZCDRMY.gif> Message ID: ***@***.*** ***@***.***> >