fixes #1050
wielebenwir/commonsbooking pull request #1051
Opened 2022-05-17 12:05 UTC by hansmorb

2022-05-17 21:25 UTC, chriwen commented
@hansmorb Da sollte @markus-mw nochmal drüberschauen. Ich erinnere mich, dass dieses nopaging irgendwie notwendig war für bestimmte Abfragen. Die Funktion ist ja an einer recht zentralen Stelle.
@markus-mw Kannst du das bitte mal checken?

2022-05-20 11:53 UTC, markus-mw requested changes

2022-05-20 11:53 UTC, markus-mw commented on src/Repository/BookablePost.php
> -
Wenn der Parameter fehlt, werden nur maximal 10 posts zurückgegeben. Die Anpassung wird mit großer Wahrscheinlichkeit zu Problemen führen.

2022-05-23 17:32 UTC, hansmorb commented on src/Repository/BookablePost.php
> -
Wie lösen wir dann das Problem? Eigentlich sollte ja dort keine pagination stattfinden, weil es auch keine Möglichkeit gibt zwischen den Seiten zu wechseln.

2022-06-03 12:21 UTC, merged