Feature/issue 764 (iCalendar Links)
wielebenwir/commonsbooking pull request #1068
Opened 2022-06-04 11:22 UTC by hansmorb

Das ist die letzte Erweiterung der gesamten iCalendar Geschichte. Über "Erweiterte Optionen" kann der Zugriff auf einen Link zu einer dynamischen iCalendar Datei in der Buchungsliste angezeigt werden.

2022-06-10 12:43 UTC, markus-mw requested changes

2022-06-10 12:43 UTC, markus-mw commented on src/View/Booking.php
> +	public static function getBookingListiCal($user = null){
@hansmorb : Ich würde das ehrlich gesagt als Service (/src/Service) sehen und die Funktion etwas aufbrechen. 100 Zeilen ist etwas viel für eine einzelne Funktion...

2022-06-24 11:37 UTC, hansmorb commented on includes/Users.php
> +	$script_location = plugin_dir_url(__DIR__) . 'src/iCalendar.php';
Hast du ein Beispiel dafür? Ich konnte da nichts dazu finden.

2022-07-01 08:37 UTC, markus-mw commented on src/Messages/BookingMessage.php
> +		$booking_user = $booking->getUserData();
Das stimmt, soweit bin ich nicht rutnergestiegen.

2022-07-01 09:24 UTC, markus-mw commented on includes/Users.php
> +	$script_location = plugin_dir_url(__DIR__) . 'src/iCalendar.php';
Ich hab das mal im Branch umgesetzt. Schau mal auf meinen letzten Commit.

2022-07-03 08:13 UTC, hansmorb commented on includes/Users.php
> +	$script_location = plugin_dir_url(__DIR__) . 'src/iCalendar.php';
Das sieht super aus, vielen Dank!

2022-07-08 11:18 UTC, markus-mw approved these changes

2022-07-08 11:18 UTC, merged