Feature/issue 697 2
wielebenwir/commonsbooking pull request #1161
Opened 2022-12-27 18:00 UTC by hansmorb

Bitte nicht mergen, nur für die Unit tests

2023-01-23 18:31 UTC, hansmorb commented
Ich sollte mir das WIRKLICH schwer überlegen, ob ich die Exceptions wie Flummis hin- und her werfen will. (Bei der HandleFormRequest)

2023-06-02 11:58 UTC, hansmorb commented
@datengraben Hey, kurze Frage, vielleicht hast du ja kurz Zeit dir das anzusehen. Ich habe das Problem, dass die Unit Tests manchmal problemlos durchlaufen und manchmal einfach gar nicht. Ich arbeite weder mit Zufallsdaten noch mit der aktuellen Uhrzeit, es ist mir ehrlich gesagt ein Rätsel. Hast du ne Ahnung woran das liegen könnte?

2023-06-02 14:32 UTC, datengraben commented
@hansmorb ich habe jetzt mal den `pull_reqeust` trigger rausgenommen, dann ist der workflow auch nicht zwei mal getriggert.

2023-06-03 11:07 UTC, datengraben commented
Die Inhalte der Arrays im [Github-Action/Test](https://github.com/wielebenwir/commonsbooking/actions/runs/5154976397/jobs/9284550926) sehen gleich aus, aber  sind manchmal nur anders sortiert ... ich habe jetzt mal `checkBookingRanges` immer nach post_date sortiert https://github.com/wielebenwir/commonsbooking/pull/1161/commits/843890357030dcc6520ae4ef093b54996be69891

2023-10-24 21:55 UTC, hansmorb commented on src/Wordpress/CustomPostType/Booking.php
> -			$this->handleFormRequest();
Das wurde vorher über den Konstruktor von dem CPT aufgerufen. Dieser Aufruf liegt jetzt separat in der Plugin.php. Das musste ich so umstellen, weil ich für die Buchungsregeln schon beim Buchungsprozess auf die Taxonomien zugreifen muss (um zu schauen ob diese zutreffen).

2024-02-12 14:29 UTC, datengraben commented
@hansmorb ich schaue mir den PR am Wochenende final an.

Für mich nur als Merker, bisher verbleibende TODOs:
- [ ] Den neuen Filter-Hook aus dem PR mit Schnittstelle und Nutzung einmal auf der [Buchungsregel-Seite](https://commonsbooking.org/wp-admin/post.php?post=2157&action=edit) und auf der [Filter-Hook-Seite](https://commonsbooking.org/wp-admin/post.php?post=2022&action=edit) dokumentieren
- [ ] Feedback von Erstellern der originalen Issues einholen

2024-02-13 18:30 UTC, hansmorb commented
> @hansmorb ich schaue mir den PR am Wochenende final an.
> 
> Für mich nur als Merker, bisher verbleibende TODOs:
> 
>     * [ ]  Den neuen Filter-Hook aus dem PR mit Schnittstelle und Nutzung einmal auf der [Buchungsregel-Seite](https://commonsbooking.org/wp-admin/post.php?post=2157&action=edit) und auf der [Filter-Hook-Seite](https://commonsbooking.org/wp-admin/post.php?post=2022&action=edit) dokumentieren

Ich habe eher schon überlegt diesen Hook rauszunehmen, als ich ein Beispiel dafür erstellen wollte ist mir nichts eingefallen, was nicht mit tiefem Verständnis von CB implementiert werden kann ergo auch nur von uns implementiert werden kann. Also wenn dann müssten sehr genau auch die Helpermethoden dokumentiert werden oder wir nehmen den Hook raus.
> 
>     * [ ]  Feedback von Erstellern der originalen Issues einholen

Zum 2.:
Die verlinkte Issue ist nur lose damit verbunden, eigentliche Anforderung kam von der flotte Berlin.

2024-02-17 17:09 UTC, datengraben requested changes
Nur kleinere Änderungen und Fragen, nichts wildes.

2024-02-17 17:10 UTC, datengraben commented
@hansmorb 

> Ich habe eher schon überlegt diesen Hook rauszunehmen, als ich ein Beispiel dafür erstellen wollte ist mir nichts eingefallen, was nicht mit tiefem Verständnis von CB implementiert werden kann ergo auch nur von uns implementiert werden kann. 

Ich finde diese Schnittstelle (Buchungsregeln) einen guten Kandidat um Arbeit/Code aus dem Core herauszuhalten. Das Thema kam ja schon vermehrt auf.

Vorteile wären:

1. Gibt es ja einige Menschen mit Coding-Skills in den Instanzen, welche zwar nicht unbedingt direkt am Core mitarbeiten wollen/können, aber ich denke in der Lage wären eine Buchungsregel selber zu schreiben.
2. Instanzen können ihre Buchungsregeln miteinander teilen. Die Flotte hat für CB1 ja schon einiges an custom-Plugins erstellt das nachgefragt wird.

Beispiele für Nicht-Core-Buchungsregeln wären zum Beispiel:

* Wenn benutzerdefinierte Meta-Werte an Post-Objekten genutzt werden die nicht im Core sind und relevant für den Buchungsprozess der Instanz sind. 
  * Eine Instanz hat an bestimmte Items ein Meta-Feld gehangen um bei z.B. Fehlverhalten o.A. zu markieren, welche Items von Usern nicht mehr ausgeliehen werden dürfen. Vorstellbar finde ich hier auch etwas wie einen "Führerschein" für ein Item, welcher dann auch z.B. in einem Meta-Wert abgelegt wird.
  * Oder ob User eine Anmeldung über eine auf dieser Instanz eingerichteten 2FA aktiviert haben.

> Also wenn dann müssten sehr genau auch die Helpermethoden dokumentiert werden oder wir nehmen den Hook raus.

Welche Helpermethoden meinst du genau?

> Zum 2.: Die verlinkte Issue ist nur lose damit verbunden, eigentliche Anforderung kam von der flotte Berlin. 

Ok.

2024-02-17 17:39 UTC, datengraben commented
> * Nutzenden nur eine "unconfirmed" Buchung gleichzeitig erlauben damit nicht ein Haufen von unbestätigten Buchungen erzeugt werden kann um die Buchungsregeln zu umgehen. Wenn zB. ein Nutzender einen nur 1 Tag pro Monat buchen kann könnte dieser einfach mehrere unbestätigte Buchungen für den gleichen Monat erzeugen und diese dann nacheinander bestätigen. Eine Buchungsprüfung wird nur bei Erstellung einer unbestätigten Buchung durchgeführt. Das ist eine Komfortfunktion, damit Nutzende nicht die ganze Buchungsstrecke durchspielen müssen nur um zu erfahren, dass die Buchung nicht möglich ist.

@hansmorb Das in einen eigenes Issue auslagern?

2024-02-17 22:36 UTC, hansmorb commented on src/Wordpress/CustomPostType/Booking.php
> -			$this->handleFormRequest();
Genau, vorher wurde über den init Post Type die registerCustomPostTypes aufgerufen die dann über Umwege den Konstruktor hier aufgerufen hat. Dieser Konstruktor wieder hat dann die handleFormRequest aufgerufen. Das habe ich jetzt da dann direkt im Hook gemacht,

2024-02-18 08:38 UTC, hansmorb commented on src/Plugin.php
> +		add_action('init', array(self::class, 'handleBookingForms'), 50);
Das reproduziert nur das ursprüngliche Verhalten wie über die registerCustomPostTypes ansonsten die Methode bei jedem Init aufgerufen wird. Ich denke mal der Request ist nicht leer, wenn eine Buchung über das Frontend erstellt wird.

2024-02-18 08:43 UTC, hansmorb commented on composer.json
> -      "includes/OptionsArray.php",
Nicht ganz! Das brauchen wir um definierte Kategorien in den Backend Options anzuzeigen. Wenn wir das drinlassen, dann lädt der Autoloader die OptionsArray bevor die Taxonomien initialisiert wurden und er kann die definierten Kategorien nicht laden. Analog habe ich das auch in PR #1409 machen müssen, weil wir dort auch Kategorien in den Optionen auswählen müssen. 

Die registerAdminOptions nimmt dann das Laden der OptionsArray vor und das wird gemacht NACHDEM CPTs und Taxonomien registriert wurden.

2024-02-18 09:35 UTC, hansmorb commented on src/Model/Booking.php
> +	public function termsApply( $term ): bool {
Du meinst den $term Parameter? Dann ist es doch egal ob int|array|string oder int|string|array, nicht?

2024-02-18 10:34 UTC, hansmorb commented on src/Model/Booking.php
> +	 * Meta value for the amount of days that have been overbooked for this booking.
Faulheit ist die Motivation. Ich will schauen wie viele Tage der Buchung überbucht wurden, das geht am besten mit dem Javascript indem ein Hidden Input ausgefüllt wird. Wenn ich das über PHP auswerten wollen würde müsste ich die CalenderData Array mit den Buchungsdaten abgleichen, das bräuchte einen ganzen Haufen eigene Logik

2024-02-18 11:13 UTC, hansmorb commented on src/Model/Booking.php
> +			$interval = $this->getStartDateDateTime()->diff($this->getEndDateDateTime()->modify("+5 min"));
Ne, hier geht es darum, dass das StartDatum als Uhrzeit immer 00:00 und das Enddatum immer 23:59 als Rückgabezeit hat. Wahrscheinlich würde hier auch +1 Minute reichen. Das ist unabhängig von der start-time und end-time. Das sind zwei unterschiedliche Werte, etwas verwirrend.

2024-02-18 11:31 UTC, hansmorb commented on src/Repository/UserRepository.php
> +			if ($value['name'] == 'Administrator') {
Stimmt, ich wollte die Adminrolle aus der Rollenauswahl rausnehmen aber habe den Übersetzungswert statt die originale RoleID genommen

2024-02-18 11:32 UTC, hansmorb commented on src/Wordpress/CustomPostType/Item.php
> +			$errormessage = \CommonsBooking\View\Booking::getError();
Genau, das hatte sich München gewünscht damit es direkt oben auf der Seite die Fehlermeldung anzeigt

2024-02-18 11:32 UTC, hansmorb commented on templates/timeframe-calendar.php
> +	        <input type="hidden" name="days-overbooked" value="0"/>
Damit das JS diesen Wert befüllen kann mit der tatsächlichen Mengen an Tagen die überbucht wurden

2024-02-18 11:40 UTC, hansmorb commented on src/Wordpress/CustomPostType/Booking.php
> +			catch (BookingDeniedException $e) {
Genau, er soll nämlich nicht Buchungen die nicht erlaubt sind als unconfirmed lassen. Sonst könnte man nochmal drauf zugreifen und sie dann bestätigen.

2024-02-18 11:55 UTC, hansmorb commented on tests/php/Wordpress/CustomPostType/BookingTest.php
> +		//two of those days are counted as overbooked, first day is still counted to maximum quota
Meinst du in der Dokumentation für die Model/Booking::setOverbookedDays ? Habe da mal etwas mehr Info ergänzt

2024-02-19 10:21 UTC, datengraben commented on src/Model/Booking.php
> +	public function termsApply( $term ): bool {
ja ich meinte nicht die Reihenfolge, sondern das es bei `termsApply` einfach nur als Typ Deklaration fehlt.

2024-02-20 20:59 UTC, hansmorb commented on src/Model/Booking.php
> +	public function isUserPrivileged(\WP_User $user = null): bool {
Das ist ne gute Frage, das weiss ich auch nicht mehr so genau. Wahrscheinlich würde die Implementierung vom  Timeframe dafür auch reichen.

2024-02-20 21:00 UTC, hansmorb commented on src/Model/Booking.php
> +	public function termsApply( $term ): bool {
Achso, weil Union Types erst seit PHP8 unterstützt werden, das ist also für abwärtskompatibilität

2024-02-21 09:08 UTC, datengraben commented on src/Plugin.php
> +		add_action('init', array(self::class, 'handleBookingForms'), 50);
Aber über die Registrierung am [`init`-Hook](https://developer.wordpress.org/reference/hooks/init/) wird `handleBookingForms` doch bei jedem Laden von Wordpress (und erfolgreichen Authentifizeren) aufgerufen.

2024-02-21 09:34 UTC, datengraben commented on src/Model/Booking.php
> +	 * Meta value for the amount of days that have been overbooked for this booking.
Ok passt für mich, an sich kann das aber natürlich client-seitig manipuliert werden. Sollte wir im Hinterkopf behalten und an geeigneter Stelle vielleicht prüfen.

2024-02-21 09:34 UTC, datengraben commented on src/Model/Booking.php
> +	public function isUserPrivileged(\WP_User $user = null): bool {
Bau es gerne aus, aber ist auch kein Blocker.

2024-02-21 09:37 UTC, datengraben commented on src/Model/Booking.php
> +			$interval = $this->getStartDateDateTime()->diff($this->getEndDateDateTime()->modify("+5 min"));
Ah jetzt sehe ich es, es handelt sich um `startDate` und nicht `startTime`

2024-02-21 09:38 UTC, datengraben commented on src/Plugin.php
> +		add_action('init', array(self::class, 'handleBookingForms'), 50);
Also so lange es hier zu keinen Problemen kommt (augenscheinlich tut es das ja nicht) können wir das auch getrennt vom Zeitpunkt des merges diskutieren. Also kein Blocker.

2024-02-21 09:40 UTC, datengraben approved these changes

2024-02-22 22:43 UTC, merged