Adds email signature
wielebenwir/commonsbooking pull request #1164
Opened 2023-01-02 22:21 UTC by datengraben

This adds email signature to the options array (settings -> 'template')
This will resolve #75 

Question: 

Is there already an function to replace a string like `{{E-Mail-Signature}}` in the body?

For exampe, when sending emails I can do either:
* If `{{E-Mail-Signature}}` is already in the body, replace the string and do not append it's contents to the body.
* If the string is not already in the body, then it's contents will be appended to the body.

2023-01-02 22:43 UTC, datengraben commented
I understand TemplateParser.php has the function to replace the template key. But at the moment I'm unsure how to properly assign a `{{...}}`-tag to the new Options array field or whether it already is useable by its name `{{Mail-Signature}}` or its id `{{emailbody_signature}}`, with the result that it get's replaced.

2023-01-04 12:27 UTC, datengraben commented
The text value of the configuration field Is now appended at the email body.
![image](https://user-images.githubusercontent.com/105302830/210554960-6888b455-77cc-4feb-99da-c7b183b05f59.png)

2023-01-04 12:30 UTC, datengraben commented
@chriwen From my view it can be merged.

2023-01-04 13:37 UTC, hansmorb requested changes

2023-01-04 14:14 UTC, chriwen commented on includes/OptionsArray.php
> +						'desc'    => commonsbooking_sanitizeHTML( __( 'E-Mail signature that will be printed at the end of the body or where every you put Mail-Signature in double brackets.', 'commonsbooking' ) ),
@hansmorb Hatte das als Kommentar im Quellcode @datengraben so vorgeschlagen. Über TemplateTag wäre tatsächlich eleganter. Dann wäre es wahrscheinlich sinnvoll im Booking-Model eine getEmailSignature zu basteln, die dann den Optionswert holt. Dann müsste sie ja über das Booking-Objekt geparsed werden können, oder?
@datengraben Willst du das mal versuchen, oder sollen wir dazu vorher nochmal kurz sprechen?

2023-01-05 13:25 UTC, datengraben commented on includes/OptionsArray.php
> +						'desc'    => commonsbooking_sanitizeHTML( __( 'E-Mail signature that will be printed at the end of the body or where every you put Mail-Signature in double brackets.', 'commonsbooking' ) ),
@hansmorb @chriwen ok habe es gepusht. Funktioniert bei mir mit `{{booking:getEmailSignature}}`

2023-01-05 13:41 UTC, datengraben commented
Wenn es jemand merged bitte squashen wenn möglich :)

2023-01-06 07:39 UTC, hansmorb approved these changes
Passt für mich.

2023-01-06 10:08 UTC, datengraben commented
Habe es jetzt selber gesquashed, wusste nicht das ich das kann.

2023-01-08 13:38 UTC, hansmorb commented on src/Messages/Message.php
> +use CommonsBooking\Settings\Settings;
Dieser import ist jetzt überflüssig, oder?

2023-01-09 07:51 UTC, datengraben commented on src/Messages/Message.php
> +use CommonsBooking\Settings\Settings;
Stimmt, ist weg.

2023-01-13 13:38 UTC, chriwen approved these changes

2023-01-13 13:38 UTC, merged