Feature/issue 1172
wielebenwir/commonsbooking pull request #1173
Opened 2023-02-03 14:35 UTC by hansmorb

close #1172 
Die isUserAllowedToEdit hat vorher gar keine "richtige" Prüfung vorgenommen, ob der User denn auch die Berechtigung "edit" für den aktuellen Post type hat. Da das für CB_Manager aber gegeben ist, macht das da keinen Unterschied. Es macht aber schon einen Unterschied, wenn andere Rollen mit möglicherweise anderen Capabilities ins Spiel kommen. Dann kann mit dem entsprechenden Haken die Berechtigung zur Bearbeitung gesetzt / entzogen werden.

2023-06-03 08:31 UTC, datengraben requested changes
Nur das eine TODO gefunden.

2023-06-03 08:31 UTC, datengraben commented on includes/Users.php
> + * TODO After PR #1141 refactor doubled code
@hansmorb TODO? Der Code soll/kann raus oder?

2023-06-03 08:48 UTC, chriwen commented
@hansmorb Ich hab das jetzt nicht testen können, kann deshalb erstmal kein Feedback zum Code geben. Eine bitte aber: Kannst du die Berechtigungs-Idee / Ansatz einmal dann noch kurz in der Doku beschreiben, damit wir auch später nochmal verstehen, wie das genau gedacht ist? Langsam wird es in Sachen Berechtigungen ja doch was komplexer ;-)
 Vielen Dank.

2023-06-03 12:11 UTC, hansmorb commented
> @hansmorb Ich hab das jetzt nicht testen können, kann deshalb erstmal kein Feedback zum Code geben. Eine bitte aber: Kannst du die Berechtigungs-Idee / Ansatz einmal dann noch kurz in der Doku beschreiben, damit wir auch später nochmal verstehen, wie das genau gedacht ist? Langsam wird es in Sachen Berechtigungen ja doch was komplexer ;-) Vielen Dank.

Das ist nur vielleicht nicht zwangsläufig was für die User Doku. 
Eigentlich sollte bei WordPress die Berechtigung "see" ermöglichen etwas zu lesen und "edit" etwas zu bearbeiten.
CB Manager haben automatisch "see" und "edit" Rechte für alle Posts (Artikel, Standorte, Buchungen,...) die ihnen zugewiesen sind.  

Mit den neuen Änderungen ist es jetzt möglich eine neue Rolle zu erstellen, die z.B. NUR See Rechte hat für Posts die ihnen zugewiesen sind. Das schließt natürlich Posts, aus die sowieso schon öffentlich sind, also eigentlich alle außer Buchungen. Kurz gesagt: Damit kannst du eine Rolle erstellen, die die Berechtigung hat BUchungen zu sehen die ihr zugewiesen sind, sie aber NICHT bearbeiten kann (quasi wie ein Read-Only CB-Manager).

Die Implementierung der Rolle an sich hängt an der Initiative. Es gibt auch einen Filter, mit denen man Nutzer selbst erstellte Rollen auf diese Art Standorten / Artikeln zuweisen kann. 
Das heißt um das Nutzen zu können müssen Inis
1. eine Custom Rolle erstellen (mit der Berechtigung cb_bookings zu sehen)
2. die dann durch den Filter jagen, damit Nutzer mit dieser Rolle einem Artikel oder Standort zugewiesen werden können 
3. und dann können diese zugewiesenen Nutzer eine Buchung nur sehen aber nicht bearbeiten.

2023-06-05 10:44 UTC, datengraben commented
@hansmorb im letzten Commit habe ich die tests für `canCancel` eingefügt, dabei ist noch Fehler bei dem Vergleich aufgefallen. Es ginge natürlich auch, wenn wir nicht casten und wieder `==` verwenden.

Ich habe es nicht geschafft einen Test-User so einzurichten, das `current_user_can(`edit_post`, ... )` für die Testbookings wahr wird. Ggf. liegt das daran das es sich hierbei um custom posts handelt. Ich habe das vorerst mal liegen gelassen.

2023-06-05 15:47 UTC, datengraben commented on src/Plugin.php
> +		// TODO if post is integer, breaks ...
Das war noch bevor ich deine Änderungen in https://github.com/wielebenwir/commonsbooking/pull/1173/commits/77bcee76140bf7b77ef3116e9f1db9c2cbaa4df2 gesehen habe.

2023-06-05 16:08 UTC, hansmorb commented
Leider konnte ich noch nicht alle Tests aktivieren, weil das Plugin nicht komplett zum Testen initialisiert wird. Also wird z.B. auch nicht die CB Manager Rolle vollständig erstellt.

2023-06-05 16:09 UTC, hansmorb commented
@datengraben Ich hoffe ich habe gerade nicht beim mergen Teil deiner Tests kaputtgemacht!

2023-06-05 21:56 UTC, hansmorb commented
@datengraben Voll gut, dass du das nochmal mit den Unit Tests angestoßen hast. Dabei ist mir aufgefallen, dass ich das Wordpress capability System noch nicht so ganz verstanden habe. Zumindest so wie es jetzt gerade ist funktioniert es nicht, die edit_post capability wird nicht richtig für den aktuellen Post Type erkannt. Zumindest geht es in den Unit Tests nicht, ich muss es natürlich auch mal im echten Wordpress ausprobieren.

2023-06-07 14:31 UTC, datengraben commented
Ok das heißt Code-mäßig ist der hier erstmal fertig oder? Du schaust nur noch lokal ob alles passt?

2023-06-07 16:26 UTC, hansmorb commented
> 

Na ja, also die Tests funktionieren so gerade leider nicht, also muss ich nochmal im Detail schauen woran es liegt. Deshalb noch nicht ready würde ich sagen.

2023-07-09 13:47 UTC, hansmorb commented
@datengraben Jetzt funktionieren auch die Tests wie erwartet. Ich hatte nur vergessen, dass die Custom Roles ja auch initialisiert werden müssen.

2023-07-09 20:53 UTC, datengraben approved these changes

2023-07-09 22:17 UTC, merged