Manuelle Datumseingabe für Timeframes
wielebenwir/commonsbooking pull request #1180
Opened 2023-02-28 10:46 UTC by hansmorb

Closes #802

2023-07-09 21:11 UTC, datengraben requested changes

2023-07-09 21:11 UTC, datengraben commented on assets/public/css/public.css
> -.cb-wrapper #calendar-footnote #calendar-footnote-colorkey .colorkey-square {
@hansmorb hast du hier vergessen die scss Änderungen zu comitten? Weil die css Files sind doch die gebauten Assets und nicht die sourcen

2023-07-09 21:11 UTC, datengraben commented on assets/admin/js/src/timeframe.js
> +                        //holidayField.show();
Hier sind noch kommentare drin

2023-07-09 21:11 UTC, datengraben commented on assets/admin/js/src/timeframe.js
> +                    if (selectedType == 3 && selectedRepetition == 'manual') {
Hier kannst du auch eqeqeq benutzen

2023-07-09 21:11 UTC, datengraben commented on assets/admin/js/src/timeframe.js
> +                    if (selectedType == 3) {
eqeqeq

2023-09-07 11:36 UTC, datengraben commented on src/Model/Timeframe.php
> +	public function addStartAndEndDate() : void {
Im Location Model haben wir eine Methode die Meta Infos aktualisiert z.B. updateLocation genannt oder im Booking Model heißt es assignBookableTimeframeFields. Wieso nicht `updatePostMetaStartAndEndDate()`

2023-09-07 11:52 UTC, datengraben commented on src/Model/Timeframe.php
> +	 * Returns type of repetition.
Super! Ich habe mal noch alle vorkommen von timeframe-repetition ersetzt mit der META_REPETITION Variable. So bekommt man schneller einen überblick.

2023-09-07 12:17 UTC, datengraben approved these changes
Ich habe alles gereviewed. Die Unit-tests habe ich nicht wirklich angeschaut, eher überflogen.

2023-09-07 12:18 UTC, datengraben commented
@hansmorb Ich habe noch selber 'timeframe-repetition' refactored.

2023-09-07 12:47 UTC, datengraben commented
@hansmorb habe versucht die Konflikte zu mergen, aber bei den Tests schaue ich nicht ganz durch. Mit den letzten Änderungen im master (https://github.com/wielebenwir/commonsbooking/commit/9f2fdd3c2619fcbb0612f42220fa71e5e80942be, https://github.com/wielebenwir/commonsbooking/commit/c13b0b6eb8fcca521cd51f1711640b0c7e61b067 und etwas länger her https://github.com/wielebenwir/commonsbooking/commit/a137852f7b9d3b50b8d2f5349f564ec250eafda2 und https://github.com/wielebenwir/commonsbooking/commit/e5f52dcf686a0e9c04ae332df596a6695d971efa sind in `Model\TimeframeTest.php` einige der auch aus diesem Branch betroffenen Unit-Tests verändert worden.

2023-09-07 14:30 UTC, hansmorb commented on src/Model/Timeframe.php
> +	 * Returns type of repetition.
Cool, vielen Dank. Mit einem Enum wäre das hier vielleicht praktischer,  irgendwann wenn wir mal auf PHP 8.1 wechseln könnten wir das machen :)

2023-09-07 15:06 UTC, hansmorb commented
Tausend Dank @datengraben . Ich stell diesen PR trotzdem nochmal zurück bis zum nächsten Feature Release.

2023-09-07 20:56 UTC, chriwen commented on src/Model/Timeframe.php
> +	public function addStartAndEndDate() : void {
@datengraben Die Methode im Booking-Model updated ja nicht nur Start und Endzeit, sondern fügt der Buchung weitere Meta-Felder hinzu. Dies hat historische Gründe, da Buchungen ja früher Timeframe-Objekte waren und wir nun diese zusätzliche Meta-Felder weiterhin benötigen, um die gebuchten und freien Zeiten zu berechnen.
Bei der Location meinst du die Funktion updateLocationCoordinates? Hier werden ja tatsächlich nur bereits vorhandene Metafelder aktualisiert. Ich hoffe, das war einigermaßen verständlich?

2023-09-08 19:00 UTC, datengraben approved these changes

2023-11-05 16:42 UTC, merged