added support for WP personal data exporter #1355
wielebenwir/commonsbooking pull request #1356
Opened 2023-09-21 02:16 UTC by hansmorb

https://developer.wordpress.org/plugins/privacy/adding-the-personal-data-exporter-to-your-plugin/
closes #1355

2023-09-21 15:20 UTC, datengraben requested changes

2023-09-21 15:23 UTC, hansmorb commented on src/Wordpress/CustomPostType/Booking.php
> +	 * TODO: FIX: We can't add pagination because of the way the @see \CommonsBooking\Repository\Booking::getForUser() works.
Ja, ist mir leider bewusst. Aber ich bin mir nich sicher wie man das paginaten könnte. Vielleicht müsste man die get Methode irgendwie anpassen?

2023-09-21 17:34 UTC, datengraben commented on src/Wordpress/CustomPostType/Booking.php
> +	 * TODO: FIX: We can't add pagination because of the way the @see \CommonsBooking\Repository\Booking::getForUser() works.
Ja das muss man auf jeden Fall.

2023-09-21 18:17 UTC, hansmorb commented on src/Wordpress/CustomPostType/Booking.php
> +	 * TODO: FIX: We can't add pagination because of the way the @see \CommonsBooking\Repository\Booking::getForUser() works.
Hmm, also mir stellt sich die Frage wie wir das überhaupt hinkriegen wollen. Die Standard WP Methode get_posts unterstützt pagination. Aber wir haben ja erst die getPostIDsByType, die alle Posts aus der Datenbank von einem bestimmten Typ zurückgibt und dann die getPostsByBaseParam die daraus die verbleibenden Posts auswählt die auf den Query passen. Ich wüsste leider nicht in welchem Schritt wir da sinnvoll pagination mit hineinbringen können.

2023-09-23 03:21 UTC, hansmorb commented on src/Wordpress/CustomPostType/Booking.php
> +	 * TODO: FIX: We can't add pagination because of the way the @see \CommonsBooking\Repository\Booking::getForUser() works.
Hab jetzt einfach ne andere Funktion genutzt

2023-10-21 14:40 UTC, datengraben requested changes

2023-10-21 14:40 UTC, datengraben commented on src/Repository/Booking.php
> +	 * @return array
Hier fehlt noch Model/Booking type annotation

2023-10-21 14:40 UTC, datengraben commented on src/Repository/Timeframe.php
> +	 * This function is not based on the WP_Query class, probably because of performance reasons.
Vielleicht eher ein `TODO Investigate` :laughing:  würde mich aber auch mal interessieren.

2023-10-21 18:49 UTC, merged