feiertage von js library automatisch beziehen
wielebenwir/commonsbooking pull request #1402
Opened 2023-11-05 21:02 UTC by hansmorb

das sind die Änderungen von #1299 neu aufgesetzt

2023-11-06 09:05 UTC, datengraben commented on src/Service/Holiday.php
> +	 * TODO: These do not necessarily need to be CMB2 fields but can just be custom HTML fields. All the necessary information is pulled through javascript already.
@hansmorb das verstehe ich nicht ganz. Was kann hier noch getan werden?

2023-11-06 09:05 UTC, datengraben commented on src/Service/Holiday.php
> +	 * Will render the holiday fields in the timeframe settings.
Hier wäre vielleicht noch interessant das die einzelnen Holidays, die User im Frontend wählen können, dann aus dem feiertagejs stammen.

2023-11-06 16:07 UTC, hansmorb commented on src/Service/Holiday.php
> +	 * TODO: These do not necessarily need to be CMB2 fields but can just be custom HTML fields. All the necessary information is pulled through javascript already.
Ich bin mir auch nicht mehr sicher, kann auch nicht mehr sagen ob das ursprünglich mal mein Kommentar war.

2023-11-13 12:36 UTC, datengraben requested changes

2023-11-13 12:36 UTC, datengraben commented on src/Service/Holiday.php
> +	 * Will render the fields in the timeframe settings where the user can define the holidays to get for the different states and years.
`different german states`

2023-11-13 12:36 UTC, datengraben commented on src/Wordpress/CustomPostType/Timeframe.php
> +
Vielleicht hier noch dabeischreiben zu welcher Formularfeld-id des CustomPostType es gehört ... also bekommt man auch so raus. Aber die Datei ist ganz schön groß es sind 400 Zeilen dazwischen.

2023-11-13 18:42 UTC, datengraben approved these changes

2023-11-13 18:45 UTC, merged