location reminder emails
wielebenwir/commonsbooking pull request #1410
Opened 2023-11-14 16:25 UTC by poilu

Added 2 email templates to the reminder tab of the CommonsBooking settings page. These notifiactions are meant to be sent to locations before items are picked up or returned (booking starts or end) and can be skipped for certain user roles. The contact emails of the locations are used and need to be set. This reminder option has to be activated for each location individually on the corresponding admin page.

2023-11-14 19:36 UTC, hansmorb commented on includes/OptionsArray.php
> +						'3'  => '03:00',
Ich sehe gerade, dass das für die reminder auch nicht so gut ist, wenn das klappt. Wir sind da auch nicht immer so konsistent drin, aber ich mal mal ein kleines ToDo daraus das oben auch umzubauen.

2023-11-14 19:48 UTC, hansmorb commented on src/Service/Scheduler.php
> +			'location-reminder-booking-start',
Das ist ja nicht nur ein reminder für den Start sondern auch das Ende der Buchung, oder?

2023-11-14 19:51 UTC, hansmorb commented on src/Service/Booking.php
> +	public static function sendBookingEndLocationReminderMessage() {
Das ist noch nicht verknüpft, oder?

2023-11-15 10:59 UTC, poilu commented on includes/OptionsArray.php
> +						'3'  => '03:00',
Ja, ich hatte mich da an den vorhandenen Feldern orientiert. Dein Vorschlag funktioniert.

2023-11-15 11:26 UTC, poilu commented
> Vielen Dank für den schönen PR! Ich habe nur ein paar Kleinigkeiten. Die Funktion der Nutzerrollenprüfung habe ich noch nicht ganz verstanden, könnte man da nicht vielleicht einfach nur für CB Manager das Senden von E-Mails auslassen?

Im Zusammenhang mit CB1 nutzen wir die Funktion, um Benachrichtigungen über Blocker-Buchungen (Usage-Restrictions) zu verhindern. Wenn wir das Plugin bei fLotte Berlin weiter nutzen, müssten wir dafür eine Lösung haben.  Vielleicht ließe sich das aber auch besser an anderer Stelle mit einem Filter lösen. Was meinst du?

2023-11-15 11:27 UTC, poilu commented on src/Service/Booking.php
> +	public static function sendBookingEndLocationReminderMessage() {
Stimmt, hatte ich übersehen.

2023-11-15 11:30 UTC, poilu commented on src/Service/Scheduler.php
> +			'location-reminder-booking-start',
Für das Buchungsende hat der Scheduler noch gefehlt - siehe fehlende Verknüpfung von sendBookingEndLocationReminderMessage()

2023-11-15 11:34 UTC, poilu commented on includes/OptionsArray.php
> +						'name' => esc_html__( 'Activate', 'commonsbooking' ),
Nicht zwangsläufig, so ist es konsistent mit den anderen allgem. Reminder-Einstellungen und es ließe sich bei Bedarf mit einem Klick abschalten und man müsste nicht bei allen Standorten nachschauen.

2023-11-15 11:52 UTC, poilu commented
> Huhu, vielen Dank für deinen PR. Lass die Übersetzungen ruhig erstmal raus, wir bauen die String später in den Master ein. Wenn du magst kannst du aber gerne die Übersetzungen in den PR schreiben, dann können wir das nachher einbauen.

Ok, dann ändere ich das wieder zurück auf den Stand vom master und merge den aktuellen Stand von da auch in den feature-Branch. Dann sollte es keine Konflikte geben, wenn der PR ins Haupt-Repo übernommen wird.

2023-11-15 16:20 UTC, hansmorb commented
> > Vielen Dank für den schönen PR! Ich habe nur ein paar Kleinigkeiten. Die Funktion der Nutzerrollenprüfung habe ich noch nicht ganz verstanden, könnte man da nicht vielleicht einfach nur für CB Manager das Senden von E-Mails auslassen?
> 
> Im Zusammenhang mit CB1 nutzen wir die Funktion, um Benachrichtigungen über Blocker-Buchungen (Usage-Restrictions) zu verhindern. Wenn wir das Plugin bei fLotte Berlin weiter nutzen, müssten wir dafür eine Lösung haben. Vielleicht ließe sich das aber auch besser an anderer Stelle mit einem Filter lösen. Was meinst du?

Ne, ich frage nun konkret weil ihr damit ja wahrscheinlich abfangen wollt, dass die Buchungen von den Menschen denen die Station gehört mit erwähnt werden. Für diesen Fall könnte man aber statt der definierten Rollen auch einfach eine Checkbox nehmen die der Station zugewiesenen Nutzenden rausnimmt.

2023-11-16 18:12 UTC, poilu commented
> > > Vielen Dank für den schönen PR! Ich habe nur ein paar Kleinigkeiten. Die Funktion der Nutzerrollenprüfung habe ich noch nicht ganz verstanden, könnte man da nicht vielleicht einfach nur für CB Manager das Senden von E-Mails auslassen?
> > 
> > 
> > Im Zusammenhang mit CB1 nutzen wir die Funktion, um Benachrichtigungen über Blocker-Buchungen (Usage-Restrictions) zu verhindern. Wenn wir das Plugin bei fLotte Berlin weiter nutzen, müssten wir dafür eine Lösung haben. Vielleicht ließe sich das aber auch besser an anderer Stelle mit einem Filter lösen. Was meinst du?
> 
> Ne, ich frage nun konkret weil ihr damit ja wahrscheinlich abfangen wollt, dass die Buchungen von den Menschen denen die Station gehört mit erwähnt werden. Für diesen Fall könnte man aber statt der definierten Rollen auch einfach eine Checkbox nehmen die der Station zugewiesenen Nutzenden rausnimmt.

So ganz abschätzen lässt sich noch nicht, wie sich mglw. das Nutzzungsszenario verändern wird. Möglicherweise brauchen wir die Blocker-Rolle gar nicht mehr. Mir scheint, es ist sinnvoll zweigleisig zufahren: die von dir vorgeschlagene Checkbox für dem Item zugeordnete CB-Manager und eine/n Action/Filter einzuführen, die/der es ermöglicht, spezifischer Emails abzufangen.

2023-11-16 18:22 UTC, hansmorb commented
Oder alternativ einen kleinen Check, ob die E-Mail vom Buchungsautor gleich
der zu benachrichtigenden E-Mail ist. Dann werden einfach doppelte Email
verhindert.

Thomas Richter ***@***.***> schrieb am Do., 16. Nov. 2023,
13:12:

> Vielen Dank für den schönen PR! Ich habe nur ein paar Kleinigkeiten. Die
> Funktion der Nutzerrollenprüfung habe ich noch nicht ganz verstanden,
> könnte man da nicht vielleicht einfach nur für CB Manager das Senden von
> E-Mails auslassen?
>
> Im Zusammenhang mit CB1 nutzen wir die Funktion, um Benachrichtigungen
> über Blocker-Buchungen (Usage-Restrictions) zu verhindern. Wenn wir das
> Plugin bei fLotte Berlin weiter nutzen, müssten wir dafür eine Lösung
> haben. Vielleicht ließe sich das aber auch besser an anderer Stelle mit
> einem Filter lösen. Was meinst du?
>
> Ne, ich frage nun konkret weil ihr damit ja wahrscheinlich abfangen wollt,
> dass die Buchungen von den Menschen denen die Station gehört mit erwähnt
> werden. Für diesen Fall könnte man aber statt der definierten Rollen auch
> einfach eine Checkbox nehmen die der Station zugewiesenen Nutzenden
> rausnimmt.
>
> So ganz abschätzen lässt sich noch nicht, wie sich mglw. das
> Nutzzungsszenario verändern wird. Möglicherweise brauchen wir die
> Blocker-Rolle gar nicht mehr. Mir scheint, es ist sinnvoll zweigleisig
> zufahren: die von dir vorgeschlagene Checkbox für dem Item zugeordnete
> CB-Manager und eine/n Action/Filter einzuführen, die/der es ermöglicht,
> spezifischer Emails abzufangen.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/wielebenwir/commonsbooking/pull/1410#issuecomment-1814986598>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABRCVSDUTLODWTXRUV3Y36LYEZJRTAVCNFSM6AAAAAA7LCYIQOVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTQMJUHE4DMNJZHA>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>

2023-11-20 15:16 UTC, poilu commented
Wegen der bestehenden Unklarheiten, ob und wie Einschränkungen gebraucht werden, hab ich den Teil mit den Nutzer-Rollen jetzt rausgenommen und stattdessen einen Filter vor dem Senden eingebaut. Dann ließe sich so etwas oder ähnliches bei konkretem Bedarf auch unabhängig vom Plugin umsetzen.

2023-11-21 18:52 UTC, hansmorb commented
Okay, wenn alles fertig ist dann stell den PR gerne auf "Review" :)

2023-11-27 16:04 UTC, hansmorb requested changes

2023-12-05 16:35 UTC, hansmorb approved these changes
Vielen Dank für die Anpassungen, das passt so für mich. Vielleicht noch zu diskutieren: Ist die Standardnachricht an die Station zu knapp gehalten?
![image](https://github.com/wielebenwir/commonsbooking/assets/6433480/f835379f-9289-4c96-b5a4-252191aad8b9)
Vielleicht sollten noch Informationen zu dem Buchenden und bei Bedarf ein Buchungscode hinzugefügt werden. Dann wäre es "out of the box" noch nützlicher.

Vorschlag:

```
<h2>Hi,</h2>
<p>The booking period for the item {{item:post_title}} at {{location:post_title}} will end soon.<br>
The booking period: {{booking:formattedBookingDate}}<br><br>
This item has been booked by {{user:first_name}} {{user:last_name}} ( {{user:user_email}} ). <br>


{{booking:getEmailSignature}}
```

2024-02-17 17:34 UTC, datengraben commented
@hansmorb diesen nicht auch? Der ist doch komplett fertig.

2024-02-17 22:24 UTC, hansmorb commented
> @hansmorb diesen nicht auch noch in 2.9 aufnehmen? Der ist doch komplett fertig.

Klar, könnten wir theoretisch machen aber ich wollte das wegen Review Kapazitäten und der Diskussion, ob wir die Standardnachricht etwas ausführlicher gestalten erstmal vertagen.

2024-02-18 16:30 UTC, poilu commented
Da für den Versand der Erinnerungsemails die gleiche Standort-Emailadresse verwendet wird, wie für die Buchungskopien, ist es momentan nicht möglich die Erinnerungsemails zu versenden, ohne auch Buchungskopien zu versenden. Letzteres passiert nämlich, sobald eine Adresse eingetragen wird, während die Erinnerungsmails durch eine Checkbox aktiviert werden. Es ist zu überlegen, ob dies nicht auch für die Buchungskopie der Fall sein sollte (es würde dem CB legacy Verhalten entsprechen).
Dafür muss aber sichergestellt werden, dass beim Plugin-Update das bisherige Verhalten beibehalten wird, also für Standorte mit eingetragenen Kontakt-Emailadressen die entsprechende Checkbox programmatisch gesetzt wird.

2024-02-29 18:58 UTC, hansmorb commented
> Da für den Versand der Erinnerungsemails die gleiche Standort-Emailadresse verwendet wird, wie für die Buchungskopien, ist es momentan nicht möglich die Erinnerungsemails zu versenden, ohne auch Buchungskopien zu versenden. Letzteres passiert nämlich, sobald eine Adresse eingetragen wird, während die Erinnerungsmails durch eine Checkbox aktiviert werden. Es ist zu überlegen, ob dies nicht auch für die Buchungskopie der Fall sein sollte (es würde dem CB legacy Verhalten entsprechen). Dafür muss aber sichergestellt werden, dass beim Plugin-Update das bisherige Verhalten beibehalten wird, also für Standorte mit eingetragenen Kontakt-Emailadressen die entsprechende Checkbox programmatisch gesetzt wird.

Habe gerade leider nicht so super viel Zeit deinen Code da gegenzulesen aber wurde das nicht mit #1515 für euch gelöst?

2024-02-29 18:59 UTC, hansmorb commented
Achso, und zu dem Upgrade: Mittlerweile sind wir ja auf 2.9 also wäre das wenn dann 2.9.1. Wenn ihr da 2.8.6. eintragt dann wird die Funktion bei einem Upgrade von 2.9 auf 2.9.1 nicht mehr ausgeführt. Es wird also nur etwas ausgeführt, was auf >=2.8.6 updatet.

2024-03-01 09:47 UTC, poilu commented
> Habe gerade leider nicht so super viel Zeit deinen Code da gegenzulesen aber wurde das nicht mit #1515 für euch gelöst?

Ja, hat sich damit erledigt. Das war mir entgangen, dass es dieses Ticket gibt.

2024-03-01 10:08 UTC, hansmorb commented
Ai sorry, dass du dir da die doppelte Arbeit gemacht hast

2024-03-18 19:01 UTC, hansmorb requested changes
Könnt ihr vielleicht noch den vorgeschlagenen Text mit den Nutzendendaten übernehmen? Und note to self ist noch Unit Tests zu bauen. Das muss aber nach dem merge geschehen, da ich nicht auf den Branch pushen kann.

2024-03-19 17:33 UTC, hansmorb commented
@datengraben Kannst du mir vielleicht helfen, ich komme hier mit den Tests nicht weiter. Wollte einfach nur mit einem Mock testen, ob die Methode aufgerufen wird. Wenn ich im Debugger durchsteppe sehe ich eindeutig, dass triggerMail aufgerufen wird aber es wird leider nicht erkannt. Hast du eine Idee?

2024-03-20 21:53 UTC, hansmorb approved these changes
@datengraben Kannst du da nochmal drüberschauen? Ich habe jetzt doch ein wenig mehr refactored, primär habe ich den MessageRecipient als Klasse hinzugefügt, damit auch E-Mails an Personen versendet werden können die kein \WP_User sind (wie z.B. die Location Emails).

Dann ist mir noch aufgefallen, dass die Service\Booking Klasse viele Methoden enthält die einfach nur Logik nachbauen die eigentlich so schon im Repository existieren, die Funktionen habe ich dann stattdessen verwendet und sie zur Sicherheit nochmal mit mehr Tests versehen. Leider habe ich es nicht hingekriegt auch funktionierende Tests für die Klasse zu schreiben aber da es jetzt nicht mehr von ungetesteten Queries abhängt ist das vielleicht sicherer als die vorherige Implementierung.

2024-04-04 14:56 UTC, hansmorb approved these changes

2024-04-25 11:42 UTC, merged