Try to increase quality of the codebase
wielebenwir/commonsbooking pull request #1654
Opened 2024-11-01 11:27 UTC by datengraben

@hansmorb 

* Fixes missing imports, typos in type hints (though syntactically correct)
* Adds or fixes docblocks
* Adds missing return statements of functions that are not void

2024-11-12 16:47 UTC, hansmorb requested changes
Nur Kleinigkeiten und Klarifizierungen. Ich kann leider nicht bei jeder geänderten Codestelle das manuell testen, ich verlasse mich jetzt da mal auf unsere automatisierten Tests.

2024-11-14 08:28 UTC, datengraben commented on src/API/AvailabilityRoute.php
> +				return new WP_REST_Response( $data, 200 );
Die Liste die im `$data` Objekt genutzt wird,  wird zu Beginn leer initialisiert. Sollte also einfach ein ein JSON Objekt mit leerer Liste returnieren. Dafür könnten wir aber auch einen Test hinzufügen.

2024-11-14 08:33 UTC, datengraben commented on src/Map/BaseShortcode.php
> +	final public function __construct() { }
Die Klasse verwendet einen Konstruktor Aufruf der Form `new static()`. Dieser Aufruf steht hier im abstrakten Typ und ruft aber immer den Konstruktor der *erbenden* Klasse auf. Wenn die erbende Klasse den Konstruktor überschreibt und z.B. Parameter hinzufügt funktioniert der Code nicht mehr. Daher ist eine Möglichkeit das überschreiben des Konstruktor (durch erbende Klassen) zu verbieten.

Das basiert auf [diesem Finding](https://phpstan.org/blog/solving-phpstan-error-unsafe-usage-of-new-static) der statischen Code Analyse Tools phpstan.

Das hätte ich vielleicht reinschreiben können. Also die Motivation ist Fehler zur Laufzeit zu vermeiden, die schon zur Compile-Zeit absehbar sind.

2024-11-14 08:46 UTC, datengraben commented on src/Wordpress/CustomPostType/Map.php
>  	public static function replace_map_link_target() {
Mh es gibt einige CB1 Funktionen die zwar ungenutzt aussehen, ich habe die nur nicht angefasst, weil ich nicht weiß ob die doch jemand verwendet? Wir können sie ja deprecaten und ankündigen wann wir sie rauswerfen.

2024-11-14 08:46 UTC, datengraben commented on src/Wordpress/Widget/UserWidget.php
> +		return ''; // Parent class returns string, not used
Habe es nicht getestet, da PHP null returniert, wenn kein return statement existiert. Mit der Zeile Erfüllen wir ja nur die Schnittstelle durch die Eltern-Klasse. Ich denke hier sollte nichts kaputt gehen, das eigentliche Ergebnis wird ja zwei Zeilen darüber bereits zurückgeschrieben. 

Andere Plugins implementieren das genauso (z.B. [Polylang in deren [Languages Widget](https://github.com/polylang/polylang/blob/0213b30ab2fde627a7a8c3be2fa8e4a83949639a/include/widget-languages.php#L172))

2024-11-20 17:59 UTC, hansmorb commented on src/API/AvailabilityRoute.php
> +				return new WP_REST_Response( $data, 200 );
Wenn wir irgendwie unkompliziert die Validität von der REST Response testen können.

2024-11-20 18:00 UTC, hansmorb commented on src/Map/BaseShortcode.php
> +	final public function __construct() { }
Okay! Aber aktuell überschreiben wir den Konstruktor noch nicht, oder?

2024-11-20 18:02 UTC, hansmorb commented on src/Service/BookingRuleApplied.php
> +						$ruleParams,
Das stimmt, kann ich leider auch nicht mehr nachvollziehen!

2024-11-20 18:03 UTC, hansmorb commented on src/Wordpress/CustomPostType/Map.php
>  	public static function replace_map_link_target() {
Ich bin mir zu 99% sicher, dass das nicht mehr genutzt wird. Also wir können es gerne deprecaten und mit 2.11 rauswerfen.

2024-11-20 18:12 UTC, hansmorb approved these changes
Funktionsmäßig scheint nix kaputt zu gehen!

2024-11-21 07:42 UTC, datengraben commented on src/API/AvailabilityRoute.php
> +				return new WP_REST_Response( $data, 200 );
Ja das können wir schon ... https://github.com/wielebenwir/commonsbooking/blob/master/tests/php/API/AvailabilityRouteTest.php#L71

2024-11-21 07:44 UTC, datengraben commented on src/Map/BaseShortcode.php
> +	final public function __construct() { }
Nein in der Codebase des Core nicht ... hier geht es darum zukünftige Laufzeit-Fehler zu vermeiden. Sowas würde zur Compile-Zeit nur mit einem Statischen Code Analyse Tool auffallen.

2024-11-21 07:46 UTC, datengraben commented
Dann sind folgende Punkte noch offen:

* [ ] Kommentar für Deprecation
* [ ] Rest-Routen Test für Availibility
* [ ] ggf. noch einen Test fürs Widget

2024-11-22 07:44 UTC, datengraben commented on src/Wordpress/CustomPostType/Map.php
>  	public static function replace_map_link_target() {
Ok habe es jetzt mal kommentiert. Wenn du den Code durchsuchst siehst du das `replace_map_link_target` in einer action hook auftaucht, dort aber nur angewendet wird wenn post types dem cb1 post type entsprechen. Wenn ich es richtig verstehe, also nur vor einer Migration?

2024-11-22 08:05 UTC, datengraben commented on src/API/AvailabilityRoute.php
> +				return new WP_REST_Response( $data, 200 );
Ok Test ist als AvailibilityRouteEmptyTest drin.

2024-11-22 08:07 UTC, datengraben commented
@hansmorb habe jetzt erstmal keinen Test fürs Widget geschrieben.

2024-11-22 09:38 UTC, hansmorb commented
> @hansmorb habe jetzt erstmal keinen Test fürs Widget geschrieben.

Das Widget lässt sich leider auch nur mit dem https://wordpress.com/plugins/classic-widgets Plugin nutzen, da die Widgets mittlerweile auch über den Block-Editor laufen.

2024-11-25 12:51 UTC, datengraben commented
> Das Widget lässt sich leider auch nur mit dem https://wordpress.com/plugins/classic-widgets Plugin nutzen, da die Widgets mittlerweile auch über den Block-Editor laufen.

@hansmorb das gehört auch irgendwo für die User dokumentiert.

z.B. auf dieser Seite: https://commonsbooking.org/docs/einstellungen/widget/

> Funktionsmäßig scheint nix kaputt zu gehen!

@hansmorb dann würde ich es auch mal mergen? Wenn oben die offenen Unterhaltungen so für dich passen, passt es für mich auch.

2024-12-02 14:14 UTC, merged