Draft: Fix the autoloader to enable local development
wielebenwir/commonsbooking pull request #1656
Opened 2024-11-01 18:24 UTC by datengraben

This is work in progress, do not merge it.

This PR should fix the composer autoloader to enable the following:

* [x] execution of phpunit (from `vendor/bin`)
* [x] execution of phpcs (from `vendor/bin`)

It accomplishes it because I moved the includes out of the autoloading process (fixes phpunit execution) and removed the cmb2-field-ajax-search dependency (fixes phpcs execution).

So to finish this pr the following needs to be done.

* [ ] Find a way that the above still works, but also re-add the `ed-itsolutions/cmb2-field-ajax-search`  dependency.

### Problem

The `ed-itsolutions/cmb2-field-ajax-search` dependency registers itself in the autoloader.files directive very early. See: https://github.com/Ed-ITSolutions/cmb2-field-ajax-search/blob/18f11794eef0ac638041192f25311580f68ef90a/composer.json#L16

But it has no own autoloader or bootstrapping files, so it won't load wordpress definitions on its own.

So the plugin file depends on wordpress definitions `do_action` etc., which are not loaded at this moment.
https://github.com/Ed-ITSolutions/cmb2-field-ajax-search/blob/18f11794eef0ac638041192f25311580f68ef90a/cmb2-field-ajax-search.php#L24

Because of this, the autoloading process of commonsbooking fails, but the autoload of any other plugin, that depends on it will fail too.

2024-11-01 20:28 UTC, datengraben commented
@hansmorb ok jetzt habe ich doch eine Lösung gefunden. Ich habe es aber noch nicht bei uns im Staging getestet.

2024-11-13 17:34 UTC, hansmorb requested changes
Super! Die AJAX Suche funktionierte auch nach meinen Tests immer noch. Wenn wir jetzt noch die Workflows updaten, sodass die auch die composer Version verwenden und die README aktualisieren wäre das für mich good to go. Dann können wir in Zukunft einfach PHPUnit upgraden indem wir die Version in der composer.json erhöhen.

2024-11-22 08:17 UTC, datengraben commented
@hansmorb hier habe ich jetzt was reingeschrieben.
https://github.com/datengraben/cmb2-field-ajax-search/blob/master/readme.md

Ich würde das gerne nach Wielebenwir umziehen, habe aber die Berechtigung nicht.


Und vielleicht kannst du im Repo https://github.com/wielebenwir/cmb-field-select2 dieselbe Änderung bzw. Info in die Readme schreiben. Habe dort auch keinen Zugriff.

2024-11-22 09:36 UTC, hansmorb approved these changes

2024-11-25 09:50 UTC, merged