Fix attributes
wielebenwir/commonsbooking pull request #1682
Opened 2024-12-02 09:18 UTC by janschoenherr

2025-02-05 19:10 UTC, datengraben requested changes

2025-02-05 19:10 UTC, datengraben commented on src/CB/CB1UserFields.php
> +                    <input type="text" name="address" id="address"
Why change the adress field to text? I think it should be possible to use multiple lines, the change to `text` would change that.

ASAIK its also legacy code.

2025-02-05 19:10 UTC, datengraben commented on src/Wordpress/Widget/UserWidget.php
> +                      name="<?php echo esc_attr( $this->get_field_name( 'text' ) ); ?>" cols="30"
This is fine.

2025-02-05 21:02 UTC, janschoenherr commented on src/CB/CB1UserFields.php
> +                    <input type="text" name="address" id="address"
I can change it back of course. I just don't remember, that there has ever been an input with type textarea. I think all modern browsers render it as input type text. If you do want multiple lines, maybe change it to an <textarea> element?

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#input_types

2025-02-06 23:59 UTC, datengraben commented on src/CB/CB1UserFields.php
> +                    <input type="text" name="address" id="address"
ha thats true, I'd overlooked it.

2025-02-07 00:01 UTC, datengraben commented
@janschoenherr sorry. unfortunately, the reformatting changes are just getting in the way of merging it.

2025-02-07 00:01 UTC, datengraben approved these changes

2025-02-07 08:57 UTC, janschoenherr commented
I rebased the changes 🙋‍♂️

2025-03-24 10:03 UTC, merged