code cleanup
wielebenwir/commonsbooking pull request #1686
Opened 2024-12-02 13:47 UTC by janschoenherr

2024-12-02 14:13 UTC, datengraben commented
@janschoenherr thank you for your contributions and for this PR! 

Because there exists already an unmerged but accepted pull with similar changes https://github.com/wielebenwir/commonsbooking/pull/1654 I will merge it and update this branch accordingly.

2024-12-02 14:20 UTC, datengraben commented
@janschoenherr Or you can rebase/merge yourself. After all, these are your changes :)

2024-12-02 14:58 UTC, janschoenherr commented
Thanks, I rebased the PR 🙋‍♂️

2024-12-09 09:17 UTC, hansmorb requested changes
Danke dir! Wenn man schon mal dran ist, sind mir auch noch ein paar Sachen aufgefallen. Dann wird das eine runde Sache.

2024-12-09 11:14 UTC, janschoenherr commented on src/Messages/LocationBookingReminderMessage.php
> +			$this->SendNotificationMail();
Finde ich auch schönher ;-)

2024-12-09 11:16 UTC, janschoenherr commented on includes/TemplateParser.php
>  function commonsbooking_getCBType( $type ) {
Das würde ich glaube ich nur machen, wenn der $type parameter auch auf string coerced wird. Vielleicht ändert man die return types lieber in einem separaten commit?

2024-12-09 11:17 UTC, janschoenherr commented on src/Model/Week.php
>  	protected $year;
Siehe den Kommentar von oben, vielleicht lieber in einem separaten commit?

2024-12-17 17:32 UTC, hansmorb commented on src/Service/Scheduler.php
>  	private function unscheduleJob() {
Das sollte noch in der Doku vermerkt werden, ansonsten passt alles für mich!

2024-12-17 17:34 UTC, hansmorb requested changes
Nur noch der Docstring für den Return Type der unscheduleJob Methode.

2024-12-19 13:23 UTC, janschoenherr commented on src/Service/Scheduler.php
>  	private function unscheduleJob() {
Du meinst \WP_Error kann nicht zurückkommen?

2025-02-05 19:13 UTC, datengraben approved these changes

2025-02-05 19:13 UTC, hansmorb approved these changes

2025-02-05 19:14 UTC, merged