Plugin: Fix wp translation access
wielebenwir/commonsbooking pull request #1711
Opened 2024-12-31 15:47 UTC by datengraben

Closes #1710 

Uses static access on $postType variable

* Refactors methods to use class-string based lists instead of objects of custom post types.

2025-01-04 12:47 UTC, datengraben commented
@hansmorb mit https://github.com/wielebenwir/commonsbooking/pull/1711/commits/9dde2bfe765d86e580a0993b26e93fbbedf9dfca jetzt fertig zum Review.

2025-02-06 12:59 UTC, hansmorb requested changes

2025-02-06 12:59 UTC, hansmorb commented on src/Plugin.php
> +				return ($type)::$postType;
Wäre es hier nicht vielleicht besser die statische getPostType Methode zu nehmen? Die fungiert ja so ein bisschen als getter für die Property.

2025-02-06 12:59 UTC, hansmorb commented on src/Plugin.php
> +			foreach ( self::getCustomPostTypeClasses() as $customPostType ) {
Hier würde ich den Call auf getCustomPostTypes beibehalten und dafür den Call in #L1017 auf getPostType rausnehmen.

2025-02-06 12:59 UTC, hansmorb commented on src/Plugin.php
>  	 * All CustomPostType classes extend the CustomPostType class and must be registered in this method.
Die Dokumentation muss jetzt auf die getCustomPostTypeClasses Methode.

2025-02-07 00:08 UTC, datengraben commented on src/Plugin.php
> +				return ($type)::$postType;
ja

2025-02-07 00:08 UTC, datengraben commented on src/Plugin.php
> +			foreach ( self::getCustomPostTypeClasses() as $customPostType ) {
stimmt

2025-02-07 00:08 UTC, datengraben commented on src/Plugin.php
> +	 * @since 2.10 only returns custom post type enum string
@datengraben das darf ich nicht vergessen.

2025-02-07 00:13 UTC, datengraben commented on src/Plugin.php
>  	 * All CustomPostType classes extend the CustomPostType class and must be registered in this method.
Mh an sich stimmt die Beschreibung ja noch für die Methode. Ich persönlich finde den den Ort im Plugin.php eher etwas unschön.

Ich habe mal noch auf die Classes Methode verwiesen.

2025-02-07 00:15 UTC, datengraben commented on src/Plugin.php
> +			foreach ( self::getCustomPostTypeClasses() as $customPostType ) {
Wobei das geht nicht, unten wird ja noch getView aufgerufen.

2025-02-10 23:34 UTC, datengraben commented on src/Plugin.php
> +			foreach ( self::getCustomPostTypeClasses() as $customPostType ) {
passt für dich oder?

2025-02-10 23:34 UTC, datengraben commented on src/Plugin.php
>  	 * All CustomPostType classes extend the CustomPostType class and must be registered in this method.
passt das auch?

2025-02-11 19:52 UTC, datengraben commented on src/Plugin.php
> +				return $type::$postType;
Ok ist drin.

2025-02-11 19:53 UTC, datengraben commented
@hansmorb fertig.

2025-02-11 22:45 UTC, hansmorb approved these changes

2025-02-11 22:46 UTC, merged