added admin message class
wielebenwir/commonsbooking pull request #480
Opened 2021-01-29 22:47 UTC by chriwen

@markus-mw Hab eine AdminMessage-Klasse hinzugefügt, die das erzeugen von Admin-Notices vereinfacht.
Schau mal drauf und wenn das so passt, dann bitte mergen und gerne die Klasse generell für alle Admin-Notices verwenden. 

Merci.

2021-02-01 20:04 UTC, markus-mw commented on src/Wordpress/Options/AdminOptions.php
> +            new AdminMessage($message);
Was möchtest du mit der Zeile erreichen? An und für sich macht die nix.

2021-02-01 20:06 UTC, markus-mw requested changes
Bis auf die Sache mit der Zeile, in der du eine neue AdminMessage instanziierst, ohne was damit zu machen. Passt das. Geht es dabei nur darum die add_action im Constructor auszulösen?

2021-02-01 22:04 UTC, chriwen commented
@markus-mw danke fürs prüfen. Ja, genau.  Ich dachte, dass damit der constructor durchlaufen wird und dann die add_action auslöst und so die Message auch ausgegeben wird. Ist dem nicht so? Wie könnte man das besser / richtig machen?

2021-02-05 13:27 UTC, markus-mw commented
@chriwen : Hab grad verstanden, warum du das so gemacht hast. Passt.

2021-02-05 13:27 UTC, merged