unifies filter hook names
wielebenwir/commonsbooking pull request #981
Opened 2022-03-28 22:07 UTC by hansmorb

solves #938

2022-03-29 11:15 UTC, danielappelt requested changes
See my comment..

2022-03-29 15:40 UTC, hansmorb commented
Danke, das erste ist mir durch die Lappen gewitscht. Da die zweite Funktion, wie es scheint, deprecated ist und active_plugins ein WP Filter ist würde ich das mal so lassen.

2022-03-30 07:46 UTC, danielappelt reviewed
Ich bin noch ein bisschen unglücklich mit dem ```active_plugins```-Filter. Ein Wordpress-Filter scheint es nicht zu sein: https://github.com/WordPress/wordpress-develop/search?q=active_plugins&type=code

Vielleicht sollte man zumindest einen Kommentar ergänzen, dass da noch was zu tun ist oder aber die Methode deprecated ist?

2022-03-30 08:15 UTC, hansmorb commented
Stimmt, das scheint ein Woocommerce filter zu sein. Ich war mir nicht zu 100% sicher, ob die Funktion wirklich deprecated ist @markus-mw @chriwen ?

2022-04-24 20:32 UTC, chriwen commented
@hansmorb @danielappelt Ich denke, dieser active_plugins kann komplett raus. Das wird noch ein Überbleibsel aus dem Flotte-Map-Plugin sein. 
@hansmorb Kannst du es mal entfernen und kurz testen, ob das Auswirkungen auf die Karte hat? in CB2 selbst wird es nicht verwendet.

2022-04-29 10:15 UTC, hansmorb commented
Karte funktioniert immer noch ohne Probleme!

2022-04-29 10:21 UTC, merged